spring.application.name=demo
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.datasource.url=jdbc:mysql://localhost:3306/dataSystem
spring.datasource.username=kita39
spring.datasource.password=564219Abcd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pokiji.ryuki@gmail.com
spring.mail.password=bkvo bdvo bxtj bxbe

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true